# Generated by Django 3.2.10 on 2022-03-24 05:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SibAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('api_key', models.CharField(help_text="Dapatkan API-KEY di <a href='https://edikartono.com/' target='_blank' rel='noopener'>API KEY</a>", max_length=255)),
            ],
            options={
                'verbose_name_plural': 'API KEY',
            },
        ),
    ]
