# Generated by Django 3.2.10 on 2022-02-04 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('corecode', '0001_initial'),
        ('akun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myakun',
            name='skills',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='corecode.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='myakun',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
