# Generated by Django 3.2.10 on 2022-03-24 05:24

import akun.models
import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AkunGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Member', max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BioAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_bio', models.CharField(max_length=255)),
                ('full_bio', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_social', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=akun.models.upload_to_path)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('set_as_profile', models.BooleanField(default=True)),
                ('akun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_photo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyAkun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alamat', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('P', 'Male'), ('W', 'Female')], max_length=10, null=True)),
                ('akun_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akun.akungroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=75, null=True)),
                ('email', models.EmailField(help_text='Email tidak akan ditampilkan', max_length=254, null=True)),
                ('teks', models.TextField(validators=[django.core.validators.MaxLengthValidator(250)], verbose_name='tulis komentar kamu')),
                ('cmdate', models.DateTimeField(auto_now_add=True, verbose_name='Comment date')),
                ('active', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_delete_comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cmdate'],
            },
        ),
    ]
