# Generated by Django 3.2.10 on 2022-03-15 21:47

import akun.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corecode', '0001_initial'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AkunGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Member', max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyAkun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile', models.ImageField(blank=True, null=True, upload_to=akun.models.upload_to_path)),
                ('nomor_hape', models.CharField(blank=True, max_length=17, null=True)),
                ('alamat', models.CharField(blank=True, max_length=255, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('P', 'Male'), ('W', 'Female')], default='P', max_length=10)),
                ('akun_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='akun.akungroup')),
                ('skills', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='corecode.UUIDTaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=75, null=True)),
                ('email', models.EmailField(help_text='Email tidak akan ditampilkan', max_length=254, null=True)),
                ('teks', models.TextField(validators=[django.core.validators.MaxLengthValidator(250)], verbose_name='tulis komentar kamu')),
                ('cmdate', models.DateTimeField(auto_now_add=True, verbose_name='Comment date')),
                ('active', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_delete_comment', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posts.posts')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='akun.comments')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-cmdate'],
            },
        ),
    ]
