# Generated by Django 3.2.10 on 2022-03-24 05:24

import corecode.manager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('akun', '0001_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corecode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='posts.posts'),
        ),
        migrations.AddField(
            model_name='comments',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='akun.comments'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bioaccount',
            name='akun',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_bio', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bioaccount',
            name='skills',
            field=corecode.manager.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='corecode.UUIDTaggedItem', to='taggit.Tag', verbose_name='skills'),
        ),
    ]
